<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Jannats-Air.fios-router.home" failures="1" tests="1" name="Surefire test" time="10.193" errors="0" timestamp="2021-10-28T15:53:21 EDT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="9.494">
    <failure type="java.lang.AssertionError" message="expected [Thank you for sign up] but found [Thank you for sign up, here your id - TTCVhSny]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for sign up] but found [Thank you for sign up, here your id - TTCVhSny]
at pageObject.signupPage.getThankYouMessage(signupPage.java:155)
at stepDef.signupStep.iShouldSeeThankYouForSignUpMessage(signupStep.java:45)
at âœ½.I should see Thank you for sign up message(file:///Users/jannatulnayeem/Documents/QA_Automation/GitProject/CucumberBDD_June2021/src/test/java/feature/signup.feature:9)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Surefire test -->
